version: '3'

services:
  bot:
    build: .
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PUBLIC_URL=https://your-domain.com
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.ini:/app/config.ini